[package]
name = "aoc-2023"
version = "0.1.0"
edition = "2021"

[lib]
bench = false

[dependencies]
aoc-runner = "0.3.0"
aoc-runner-derive = "0.3.0"
bstr = "1.8.0"
identity-hash = "0.1.0"
lazy-regex = "3.1.0"
nom = "7.1.3"
regex = "1.10.2"
thiserror = "1.0.50"
